#76: Read markdown content from std input
37108/md2bg pull request #77
Opened 2019-11-23 07:31 UTC by 515hikaru

Closes #76 

[tj/commander\.js](https://github.com/tj/commander.js/) を使って `-s` または `--stdin` オプションで標準入力を読み込めるようにしました。

2019-11-23 07:38 UTC, 515hikaru commented
commander.js を利用したことで、自動で `-h` または `--help` オプションが使えるようになっています。

引数の名前などを設定していないので、現在の help の出力はこんな感じです。

```
Usage: index [options]

Options:
  -s, --stdin  read standard input
  -h, --help   output usage information
```

help出力をよりわかりやすくすることは今回のスコープからははずれると思ったので、現時点では対処していません。

2019-11-25 02:33 UTC, 37108 requested changes
対応ありがとうございます。こちらのレビューが遅くなってしまい申し訳ありません。
2点だけ変更をお願いします。

package.jsonのバージョンを`0.6.0`にあげて貰ってもよろしいでしょうか。

https://github.com/37108/md2bg/blob/3e0d7d929c788b4ce5d4ae46a550762bb5eb7728/package.json#L4

importの順序を`md2bg`が一番下でかつ、上の3つとの間に空行があると嬉しいです。

https://github.com/37108/md2bg/blob/3e0d7d929c788b4ce5d4ae46a550762bb5eb7728/src/bin/index.ts#L2-L5

2019-11-25 02:35 UTC, 37108 approved these changes
対応ありがとうございます。こちらのレビューが遅くなってしまい申し訳ありません。
2点変更をお願いします。

package.jsonのバージョンを`0.6.0`にあげて貰ってもよろしいでしょうか。

https://github.com/37108/md2bg/blob/3e0d7d929c788b4ce5d4ae46a550762bb5eb7728/package.json#L4

importの順序を`md2bg`が一番下でかつ、上の3つとの間に空行があると嬉しいです。

https://github.com/37108/md2bg/blob/3e0d7d929c788b4ce5d4ae46a550762bb5eb7728/src/bin/index.ts#L2-L5

2019-11-25 02:38 UTC, 37108 commented
@515hikaru 
GitHub側でBadGateway出た後に再レビューをした結果として同一コメントでRequested ChangesとApprovedが出てしまいました。申し訳ありません。

前者のRequested Changesが正しく変更箇所の修正をお願いします。

2019-11-25 15:48 UTC, 515hikaru commented
@37108 修正しました。

2019-11-26 01:06 UTC, 37108 approved these changes
LGTM

2019-11-26 01:08 UTC, merged

2019-11-26 03:06 UTC, 515hikaru commented
Thank you!